# Project 9

One of my good friends Clara absolutely loves this show called Taskmaster which she got me hooked on my sophomore year. The show is hosted by two comedians, Greg Davis and Alex Horne, and the premise is that they invite 5  comedians onto the show each season and challenge them to do some ridiculous tasks. Some examples of tasks include: not blinking for the longest time, making a Swedish man blush, and getting to a microwave in time to stop it from making soup too hot by taking as few steps as possible.

On Data is Plural, I found data compiled by a Reddit user who went through the website Taskmaster.info and created a number of datasets containing general demographic information about the contestants, as well as more specific information like how many times they cursed over the course of their respective series.

One thing the show has been criticised for is its lack of representation of female comedians, with female comedians usually making up 1, at most 2, of the five contestants. At times, it appears that Greg Davis, who orchestrates the show, seems to openly favor the male contestants, what with challenges being things like "Who can tie a tie the fastest?" or having a tendency to give more points to male contestants than female contestants. I am curious to see if this is true and if the dataset corroborates that Greg has this tendency against women.

In [78]:
import requests
import json

import pandas as pd
import numpy as np

In [79]:
people_url = 'https://prettygr.im/tdlm/taskmaster/people.json?_labels=on'

In [80]:
people_response = requests.get(people_url)

In [81]:
people_json = people_response.json()

In [82]:
people_json

{'database': 'taskmaster',
 'table': 'people',
 'is_view': False,
 'human_description_en': '',
 'rows': [{'id': 1,
   'series': None,
   'seat': None,
   'name': 'Alex Horne',
   'dob': '1978-09-10',
   'gender': 'M',
   'hand': 'R',
   'team': None,
   'champion': 0,
   'TMI': 32},
  {'id': 2,
   'series': None,
   'seat': None,
   'name': 'Greg Davies',
   'dob': '1968-05-14',
   'gender': 'M',
   'hand': 'R',
   'team': None,
   'champion': 0,
   'TMI': 19},
  {'id': 3,
   'series': {'value': 1, 'label': 'Series 1'},
   'seat': 1,
   'name': 'Frank Skinner',
   'dob': '1957-01-28',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 1, 'label': 'Frank and Tim'},
   'champion': 0,
   'TMI': 56},
  {'id': 4,
   'series': {'value': 1, 'label': 'Series 1'},
   'seat': 2,
   'name': 'Josh Widdicombe',
   'dob': '1983-04-08',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 2, 'label': 'Josh, Roisin and Romesh'},
   'champion': 1,
   'TMI': 69},
  {'id': 5,
   'series': {'value': 1, 'label': 'Series 1'},
   'seat': 3,
   'name': 'Roisin Conaty',
   'dob': '1979-03-26',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 2, 'label': 'Josh, Roisin and Romesh'},
   'champion': 0,
   'TMI': 15},
  {'id': 6,
   'series': {'value': 1, 'label': 'Series 1'},
   'seat': 4,
   'name': 'Romesh Ranganathan',
   'dob': '1978-03-27',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 2, 'label': 'Josh, Roisin and Romesh'},
   'champion': 0,
   'TMI': 48},
  {'id': 7,
   'series': {'value': 1, 'label': 'Series 1'},
   'seat': 5,
   'name': 'Tim Key',
   'dob': '1976-09-02',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 1, 'label': 'Frank and Tim'},
   'champion': 0,
   'TMI': 34},
  {'id': 8,
   'series': {'value': 2, 'label': 'Series 2'},
   'seat': 1,
   'name': 'Doc Brown',
   'dob': '1977-09-21',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 4, 'label': 'Doc, Joe and Katherine'},
   'champion': 0,
   'TMI': 11},
  {'id': 9,
   'series': {'value': 2, 'label': 'Series 2'},
   'seat': 2,
   'name': 'Joe Wilkinson',
   'dob': '1975-05-02',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 4, 'label': 'Doc, Joe and Katherine'},
   'champion': 0,
   'TMI': 70},
  {'id': 10,
   'series': {'value': 2, 'label': 'Series 2'},
   'seat': 3,
   'name': 'Jon Richardson',
   'dob': '1982-09-26',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 3, 'label': 'Jon and Richard'},
   'champion': 0,
   'TMI': 49},
  {'id': 11,
   'series': {'value': 2, 'label': 'Series 2'},
   'seat': 4,
   'name': 'Katherine Ryan',
   'dob': '1983-06-30',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 4, 'label': 'Doc, Joe and Katherine'},
   'champion': 1,
   'TMI': 52},
  {'id': 12,
   'series': {'value': 2, 'label': 'Series 2'},
   'seat': 5,
   'name': 'Richard Osman',
   'dob': '1970-11-28',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 3, 'label': 'Jon and Richard'},
   'champion': 0,
   'TMI': 44},
  {'id': 13,
   'series': {'value': 3, 'label': 'Series 3'},
   'seat': 1,
   'name': 'Al Murray',
   'dob': '1968-05-10',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 6, 'label': 'Al, Dave and Paul'},
   'champion': 0,
   'TMI': 43},
  {'id': 14,
   'series': {'value': 3, 'label': 'Series 3'},
   'seat': 2,
   'name': 'Dave Gorman',
   'dob': '1971-03-02',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 6, 'label': 'Al, Dave and Paul'},
   'champion': 0,
   'TMI': 27},
  {'id': 15,
   'series': {'value': 3, 'label': 'Series 3'},
   'seat': 3,
   'name': 'Paul Chowdhry',
   'dob': '1974-08-21',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 6, 'label': 'Al, Dave and Paul'},
   'champion': 0,
   'TMI': 13},
  {'id': 16,
   'series': {'value': 3, 'label': 'Series 3'},
   'seat': 4,
   'name': 'Rob Beckett',
   'dob': '1986-01-02',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 5, 'label': 'Rob and Sara'},
   'champion': 1,
   'TMI': 8},
  {'id': 17,
   'series': {'value': 3, 'label': 'Series 3'},
   'seat': 5,
   'name': 'Sara Pascoe',
   'dob': '1981-05-22',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 5, 'label': 'Rob and Sara'},
   'champion': 0,
   'TMI': 46},
  {'id': 18,
   'series': {'value': 4, 'label': 'Series 4'},
   'seat': 1,
   'name': 'Hugh Dennis',
   'dob': '1962-02-13',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 7, 'label': 'Hugh and Mel'},
   'champion': 0,
   'TMI': 20},
  {'id': 19,
   'series': {'value': 4, 'label': 'Series 4'},
   'seat': 2,
   'name': 'Joe Lycett',
   'dob': '1988-07-05',
   'gender': 'M',
   'hand': 'L',
   'team': {'value': 8, 'label': 'Joe, Lolly and Noel'},
   'champion': 0,
   'TMI': 40},
  {'id': 20,
   'series': {'value': 4, 'label': 'Series 4'},
   'seat': 3,
   'name': 'Lolly Adefope',
   'dob': '1990-09-14',
   'gender': 'F',
   'hand': 'L',
   'team': {'value': 8, 'label': 'Joe, Lolly and Noel'},
   'champion': 0,
   'TMI': 2},
  {'id': 21,
   'series': {'value': 4, 'label': 'Series 4'},
   'seat': 4,
   'name': 'Mel Giedroyc',
   'dob': '1968-06-05',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 7, 'label': 'Hugh and Mel'},
   'champion': 0,
   'TMI': 24},
  {'id': 22,
   'series': {'value': 4, 'label': 'Series 4'},
   'seat': 5,
   'name': 'Noel Fielding',
   'dob': '1973-05-21',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 8, 'label': 'Joe, Lolly and Noel'},
   'champion': 1,
   'TMI': 21},
  {'id': 23,
   'series': {'value': 5, 'label': 'Series 5'},
   'seat': 1,
   'name': 'Aisling Bea',
   'dob': '1984-03-16',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 10, 'label': 'Aisling, Bob and Sally'},
   'champion': 0,
   'TMI': 7},
  {'id': 24,
   'series': {'value': 5, 'label': 'Series 5'},
   'seat': 2,
   'name': 'Bob Mortimer',
   'dob': '1959-05-23',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 10, 'label': 'Aisling, Bob and Sally'},
   'champion': 1,
   'TMI': 42},
  {'id': 25,
   'series': {'value': 5, 'label': 'Series 5'},
   'seat': 3,
   'name': 'Mark Watson',
   'dob': '1980-02-13',
   'gender': 'M',
   'hand': 'L',
   'team': {'value': 9, 'label': 'Mark and Nish'},
   'champion': 0,
   'TMI': 65},
  {'id': 26,
   'series': {'value': 5, 'label': 'Series 5'},
   'seat': 4,
   'name': 'Nish Kumar',
   'dob': '1985-08-26',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 9, 'label': 'Mark and Nish'},
   'champion': 0,
   'TMI': 36},
  {'id': 27,
   'series': {'value': 5, 'label': 'Series 5'},
   'seat': 5,
   'name': 'Sally Phillips',
   'dob': '1970-05-10',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 10, 'label': 'Aisling, Bob and Sally'},
   'champion': 0,
   'TMI': 47},
  {'id': 28,
   'series': {'value': -1, 'label': 'CoC'},
   'seat': 1,
   'name': 'Bob Mortimer',
   'dob': '1959-05-23',
   'gender': 'M',
   'hand': 'R',
   'team': None,
   'champion': 0,
   'TMI': 42},
  {'id': 29,
   'series': {'value': -1, 'label': 'CoC'},
   'seat': 2,
   'name': 'Josh Widdicombe',
   'dob': '1983-04-08',
   'gender': 'M',
   'hand': 'R',
   'team': None,
   'champion': 0,
   'TMI': 69},
  {'id': 30,
   'series': {'value': -1, 'label': 'CoC'},
   'seat': 3,
   'name': 'Katherine Ryan',
   'dob': '1983-06-30',
   'gender': 'F',
   'hand': 'R',
   'team': None,
   'champion': 0,
   'TMI': 52},
  {'id': 31,
   'series': {'value': -1, 'label': 'CoC'},
   'seat': 4,
   'name': 'Noel Fielding',
   'dob': '1973-05-21',
   'gender': 'M',
   'hand': 'R',
   'team': None,
   'champion': 0,
   'TMI': 21},
  {'id': 32,
   'series': {'value': -1, 'label': 'CoC'},
   'seat': 5,
   'name': 'Rob Beckett',
   'dob': '1986-01-02',
   'gender': 'M',
   'hand': 'R',
   'team': None,
   'champion': 0,
   'TMI': 8},
  {'id': 33,
   'series': {'value': 6, 'label': 'Series 6'},
   'seat': 1,
   'name': 'Alice Levine',
   'dob': '1986-07-08',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 11, 'label': 'Alice and Russell'},
   'champion': 0,
   'TMI': 39},
  {'id': 34,
   'series': {'value': 6, 'label': 'Series 6'},
   'seat': 2,
   'name': 'Asim Chaudhry',
   'dob': '1986-11-24',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 12, 'label': 'Asim, Liza and Tim'},
   'champion': 0,
   'TMI': 12},
  {'id': 35,
   'series': {'value': 6, 'label': 'Series 6'},
   'seat': 3,
   'name': 'Liza Tarbuck',
   'dob': '1964-11-21',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 12, 'label': 'Asim, Liza and Tim'},
   'champion': 1,
   'TMI': 59},
  {'id': 36,
   'series': {'value': 6, 'label': 'Series 6'},
   'seat': 4,
   'name': 'Russell Howard',
   'dob': '1980-03-23',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 11, 'label': 'Alice and Russell'},
   'champion': 0,
   'TMI': 33},
  {'id': 37,
   'series': {'value': 6, 'label': 'Series 6'},
   'seat': 5,
   'name': 'Tim Vine',
   'dob': '1967-03-04',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 12, 'label': 'Asim, Liza and Tim'},
   'champion': 0,
   'TMI': 63},
  {'id': 38,
   'series': {'value': 7, 'label': 'Series 7'},
   'seat': 1,
   'name': 'James Acaster',
   'dob': '1985-01-09',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 14, 'label': 'James, Phil and Rhod'},
   'champion': 0,
   'TMI': 1},
  {'id': 39,
   'series': {'value': 7, 'label': 'Series 7'},
   'seat': 2,
   'name': 'Jessica Knappett',
   'dob': '1984-11-28',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 13, 'label': 'Jessica and Kerry'},
   'champion': 0,
   'TMI': 35},
  {'id': 40,
   'series': {'value': 7, 'label': 'Series 7'},
   'seat': 3,
   'name': 'Kerry Godliman',
   'dob': '1973-11-17',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 13, 'label': 'Jessica and Kerry'},
   'champion': 1,
   'TMI': 26},
  {'id': 41,
   'series': {'value': 7, 'label': 'Series 7'},
   'seat': 4,
   'name': 'Phil Wang',
   'dob': '1990-01-22',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 14, 'label': 'James, Phil and Rhod'},
   'champion': 0,
   'TMI': 64},
  {'id': 42,
   'series': {'value': 7, 'label': 'Series 7'},
   'seat': 5,
   'name': 'Rhod Gilbert',
   'dob': '1968-10-18',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 14, 'label': 'James, Phil and Rhod'},
   'champion': 0,
   'TMI': 25},
  {'id': 43,
   'series': {'value': 8, 'label': 'Series 8'},
   'seat': 1,
   'name': 'Iain Stirling',
   'dob': '1988-01-27',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 16, 'label': 'Iain, Lou and Paul'},
   'champion': 0,
   'TMI': 57},
  {'id': 44,
   'series': {'value': 8, 'label': 'Series 8'},
   'seat': 2,
   'name': 'Joe Thomas',
   'dob': '1983-10-28',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 15, 'label': 'Joe and Sian'},
   'champion': 0,
   'TMI': 60},
  {'id': 45,
   'series': {'value': 8, 'label': 'Series 8'},
   'seat': 3,
   'name': 'Lou Sanders',
   'dob': '1985-11-24',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 16, 'label': 'Iain, Lou and Paul'},
   'champion': 1,
   'TMI': 54},
  {'id': 46,
   'series': {'value': 8, 'label': 'Series 8'},
   'seat': 4,
   'name': 'Paul Sinha',
   'dob': '1970-05-28',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 16, 'label': 'Iain, Lou and Paul'},
   'champion': 0,
   'TMI': 55},
  {'id': 47,
   'series': {'value': 8, 'label': 'Series 8'},
   'seat': 5,
   'name': 'Sian Gibson',
   'dob': '1976-07-30',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 15, 'label': 'Joe and Sian'},
   'champion': 0,
   'TMI': 23},
  {'id': 48,
   'series': {'value': 9, 'label': 'Series 9'},
   'seat': 1,
   'name': 'David Baddiel',
   'dob': '1964-05-28',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 17, 'label': 'David and Jo'},
   'champion': 0,
   'TMI': 5},
  {'id': 49,
   'series': {'value': 9, 'label': 'Series 9'},
   'seat': 2,
   'name': 'Ed Gamble',
   'dob': '1986-03-11',
   'gender': 'M',
   'hand': 'R',
   'team': {'value': 18, 'label': 'Ed, Katy and Rose'},
   'champion': 1,
   'TMI': 22},
  {'id': 50,
   'series': {'value': 9, 'label': 'Series 9'},
   'seat': 3,
   'name': 'Jo Brand',
   'dob': '1957-07-23',
   'gender': 'F',
   'hand': 'R',
   'team': {'value': 17, 'label': 'David and Jo'},
   'champion': 0,
   'TMI': 10}],
 'truncated': False,
 'filtered_table_rows_count': 117,
 'expanded_columns': ['team', 'series'],
 'expandable_columns': [[{'column': 'team',
    'other_table': 'teams',
    'other_column': 'id'},
   'members'],
  [{'column': 'series', 'other_table': 'series', 'other_column': 'id'},
   'name']],
 'columns': ['id',
  'series',
  'seat',
  'name',
  'dob',
  'gender',
  'hand',
  'team',
  'champion',
  'TMI'],
 'primary_keys': ['id'],
 'units': {},
 'query': {'sql': 'select id, series, seat, name, dob, gender, hand, team, champion, TMI from people order by id limit 51',
  'params': {}},
 'facet_results': {},
 'suggested_facets': [{'name': 'series',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/people.json?_labels=on&_facet=series'},
  {'name': 'seat',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/people.json?_labels=on&_facet=seat'},
  {'name': 'gender',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/people.json?_labels=on&_facet=gender'},
  {'name': 'hand',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/people.json?_labels=on&_facet=hand'},
  {'name': 'champion',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/people.json?_labels=on&_facet=champion'},
  {'name': 'dob',
   'type': 'date',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/people.json?_labels=on&_facet_date=dob'}],
 'next': '50',
 'next_url': 'http://prettygr.im/tdlm/taskmaster/people.json?_labels=on&_next=50',
 'private': False,
 'foreign': {'team': ['teams',
   'id',
   'series',
   'members',
   'size',
   'initials',
   'irregular'],
  'series': ['series',
   'id',
   'name',
   'episodes',
   'champion',
   'air_start',
   'air_end',
   'studio_start',
   'studio_end',
   'points',
   'tasks',
   'special',
   'TMI']},
 'allow_execute_sql': True,
 'query_ms': 12.820838019251823}

In [83]:
taskmaster_people = pd.DataFrame(columns=["id","Series", "Seat", "Name","dob","gender","hand","team","champion","TMI"])

In [84]:
for row in people_json['rows']:
    tm_id = row['id']
    series = row['series']
    if series is not None:
        series = series['label']
    seat = row['seat']
    name = row['name']
    dob = row['dob']
    gender = row['gender']
    hand = row['hand']
    team = row['team']
    if team is not None:
        team = team['label']
    champion = row['champion']
    tmi = row['TMI']
    
    new_row = {"id":tm_id,"Series": series, "Seat": seat, "Name":name, "dob":dob, "gender":gender,"hand":hand,"team":team, "champion":champion,"TMI":tmi}
    
    taskmaster_people = pd.concat([taskmaster_people, pd.DataFrame([new_row])], ignore_index=True)

In [85]:
taskmaster_people

,id,Series,Seat,Name,dob,gender,hand,team,champion,TMI
0,1,None,None,Alex Horne,1978-09-10,M,R,None,0,32
1,2,None,None,Greg Davies,1968-05-14,M,R,None,0,19
2,3,Series 1,1,Frank Skinner,1957-01-28,M,R,Frank and Tim,0,56
3,4,Series 1,2,Josh Widdicombe,1983-04-08,M,R,"Josh, Roisin and Romesh",1,69
4,5,Series 1,3,Roisin Conaty,1979-03-26,F,R,"Josh, Roisin and Romesh",0,15
5,6,Series 1,4,Romesh Ranganathan,1978-03-27,M,R,"Josh, Roisin and Romesh",0,48
6,7,Series 1,5,Tim Key,1976-09-02,M,R,Frank and Tim,0,34
7,8,Series 2,1,Doc Brown,1977-09-21,M,R,"Doc, Joe and Katherine",0,11
8,9,Series 2,2,Joe Wilkinson,1975-05-02,M,R,"Doc, Joe and Katherine",0,70
9,10,Series 2,3,Jon Richardson,1982-09-26,M,R,Jon and Richard,0,49
10,11,Series 2,4,Katherine Ryan,1983-06-30,F,R,"Doc, Joe and Katherine",1,52
11,12,Series 2,5,Richard Osman,1970-11-28,M,R,Jon and Richard,0,44
12,13,Series 3,1,Al Murray,1968-05-10,M,R,"Al, Dave and Paul",0,43
13,14,Series 3,2,Dave Gorman,1971-03-02,M,R,"Al, Dave and Paul",0,27
14,15,Series 3,3,Paul Chowdhry,1974-08-21,M,R,"Al, Dave and Paul",0,13
15,16,Series 3,4,Rob Beckett,1986-01-02,M,R,Rob and Sara,1,8
16,17,Series 3,5,Sara Pascoe,1981-05-22,F,R,Rob and Sara,0,46
17,18,Series 4,1,Hugh Dennis,1962-02-13,M,R,Hugh and Mel,0,20
18,19,Series 4,2,Joe Lycett,1988-07-05,M,L,"Joe, Lolly and Noel",0,40
19,20,Series 4,3,Lolly Adefope,1990-09-14,F,L,"Joe, Lolly and Noel",0,2
20,21,Series 4,4,Mel Giedroyc,1968-06-05,F,R,Hugh and Mel,0,24
21,22,Series 4,5,Noel Fielding,1973-05-21,M,R,"Joe, Lolly and Noel",1,21
22,23,Series 5,1,Aisling Bea,1984-03-16,F,R,"Aisling, Bob and Sally",0,7
23,24,Series 5,2,Bob Mortimer,1959-05-23,M,R,"Aisling, Bob and Sally",1,42
24,25,Series 5,3,Mark Watson,1980-02-13,M,L,Mark and Nish,0,65
25,26,Series 5,4,Nish Kumar,1985-08-26,M,R,Mark and Nish,0,36
26,27,Series 5,5,Sally Phillips,1970-05-10,F,R,"Aisling, Bob and Sally",0,47
27,28,CoC,1,Bob Mortimer,1959-05-23,M,R,None,0,42
28,29,CoC,2,Josh Widdicombe,1983-04-08,M,R,None,0,69
29,30,CoC,3,Katherine Ryan,1983-06-30,F,R,None,0,52
30,31,CoC,4,Noel Fielding,1973-05-21,M,R,None,0,21
31,32,CoC,5,Rob Beckett,1986-01-02,M,R,None,0,8
32,33,Series 6,1,Alice Levine,1986-07-08,F,R,Alice and Russell,0,39
33,34,Series 6,2,Asim Chaudhry,1986-11-24,M,R,"Asim, Liza and Tim",0,12
34,35,Series 6,3,Liza Tarbuck,1964-11-21,F,R,"Asim, Liza and Tim",1,59
35,36,Series 6,4,Russell Howard,1980-03-23,M,R,Alice and Russell,0,33
36,37,Series 6,5,Tim Vine,1967-03-04,M,R,"Asim, Liza and Tim",0,63
37,38,Series 7,1,James Acaster,1985-01-09,M,R,"James, Phil and Rhod",0,1
38,39,Series 7,2,Jessica Knappett,1984-11-28,F,R,Jessica and Kerry,0,35
39,40,Series 7,3,Kerry Godliman,1973-11-17,F,R,Jessica and Kerry,1,26
40,41,Series 7,4,Phil Wang,1990-01-22,M,R,"James, Phil and Rhod",0,64
41,42,Series 7,5,Rhod Gilbert,1968-10-18,M,R,"James, Phil and Rhod",0,25
42,43,Series 8,1,Iain Stirling,1988-01-27,M,R,"Iain, Lou and Paul",0,57
43,44,Series 8,2,Joe Thomas,1983-10-28,M,R,Joe and Sian,0,60
44,45,Series 8,3,Lou Sanders,1985-11-24,F,R,"Iain, Lou and Paul",1,54
45,46,Series 8,4,Paul Sinha,1970-05-28,M,R,"Iain, Lou and Paul",0,55
46,47,Series 8,5,Sian Gibson,1976-07-30,F,R,Joe and Sian,0,23
47,48,Series 9,1,David Baddiel,1964-05-28,M,R,David and Jo,0,5
48,49,Series 9,2,Ed Gamble,1986-03-11,M,R,"Ed, Katy and Rose",1,22
49,50,Series 9,3,Jo Brand,1957-07-23,F,R,David and Jo,0,10

First, I'm going to see how many female contestants there are versus male.

In [86]:
taskmaster_people['gender'].value_counts()

M    35
F    15
Name: gender, dtype: int64

Yeesh, not looking good.

What about the winning proportion? How many women have won a series versus a man?

In [87]:
women = taskmaster_people[taskmaster_people['gender']=='F']
men = taskmaster_people[taskmaster_people['gender']=='M']

In [88]:
women['champion'].value_counts()

0    11
1     4
Name: champion, dtype: int64

In [89]:
men['champion'].value_counts()

0    30
1     5
Name: champion, dtype: int64

Okay, of 9 seasons, 4 of the winners were female! That's about half, which is suspiciously even...

Let's look at points.

In [90]:
points_url = 'https://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on'
points_response = requests.get(points_url)
points_json = points_response.json()

In [91]:
points_json

{'database': 'taskmaster',
 'table': 'normalized_scores',
 'is_view': False,
 'human_description_en': '',
 'rows': [{'id': 1,
   'task': {'value': 1, 'label': 'The most unusual item'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 2,
   'task': {'value': 1, 'label': 'The most unusual item'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 3,
   'task': {'value': 1, 'label': 'The most unusual item'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 4,
   'task': {'value': 1, 'label': 'The most unusual item'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 5,
   'task': {'value': 1, 'label': 'The most unusual item'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 6,
   'task': {'value': 2, 'label': 'Eat as much watermelon as possible'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 7,
   'task': {'value': 2, 'label': 'Eat as much watermelon as possible'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 8,
   'task': {'value': 2, 'label': 'Eat as much watermelon as possible'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 9,
   'task': {'value': 2, 'label': 'Eat as much watermelon as possible'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 10,
   'task': {'value': 2, 'label': 'Eat as much watermelon as possible'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 11,
   'task': {'value': 3, 'label': 'Paint a horse while riding a horse'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 12,
   'task': {'value': 3, 'label': 'Paint a horse while riding a horse'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 13,
   'task': {'value': 3, 'label': 'Paint a horse while riding a horse'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 14,
   'task': {'value': 3, 'label': 'Paint a horse while riding a horse'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 15,
   'task': {'value': 3, 'label': 'Paint a horse while riding a horse'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 16,
   'task': {'value': 4, 'label': 'Empty the bathtub'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 17,
   'task': {'value': 4, 'label': 'Empty the bathtub'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 18,
   'task': {'value': 4, 'label': 'Empty the bathtub'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 19,
   'task': {'value': 4, 'label': 'Empty the bathtub'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 20,
   'task': {'value': 4, 'label': 'Empty the bathtub'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 21,
   'task': {'value': 5, 'label': 'Pop up a tent and pop on a onesie'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 22,
   'task': {'value': 5, 'label': 'Pop up a tent and pop on a onesie'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 23,
   'task': {'value': 5, 'label': 'Pop up a tent and pop on a onesie'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 24,
   'task': {'value': 5, 'label': 'Pop up a tent and pop on a onesie'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 25,
   'task': {'value': 5, 'label': 'Pop up a tent and pop on a onesie'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 26,
   'task': {'value': 6, 'label': 'Find Alex'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 0,
   'adjustment': None,
   'points': 0,
   'rank': None,
   'rigid': None,
   'spread': None,
   'scale': None,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 27,
   'task': {'value': 6, 'label': 'Find Alex'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 0,
   'adjustment': None,
   'points': 0,
   'rank': None,
   'rigid': None,
   'spread': None,
   'scale': None,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 28,
   'task': {'value': 7, 'label': 'The most impressive item'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 29,
   'task': {'value': 7, 'label': 'The most impressive item'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 30,
   'task': {'value': 7, 'label': 'The most impressive item'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 31,
   'task': {'value': 7, 'label': 'The most impressive item'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 32,
   'task': {'value': 7, 'label': 'The most impressive item'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 33,
   'task': {'value': 8, 'label': 'High-five a 55-year-old'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 34,
   'task': {'value': 8, 'label': 'High-five a 55-year-old'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 35,
   'task': {'value': 8, 'label': 'High-five a 55-year-old'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 36,
   'task': {'value': 8, 'label': 'High-five a 55-year-old'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 37,
   'task': {'value': 8, 'label': 'High-five a 55-year-old'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 38,
   'task': {'value': 9, 'label': 'Identify the contents of the pies'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 39,
   'task': {'value': 9, 'label': 'Identify the contents of the pies'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 2,
   'adjustment': None,
   'points': 2,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 40,
   'task': {'value': 9, 'label': 'Identify the contents of the pies'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '2',
   'rigid': 4.0,
   'spread': 4.0,
   'scale': 4.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 41,
   'task': {'value': 9, 'label': 'Identify the contents of the pies'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 42,
   'task': {'value': 9, 'label': 'Identify the contents of the pies'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 43,
   'task': {'value': 10,
    'label': 'Do something that will look impressive in reverse'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 0.833,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 44,
   'task': {'value': 10,
    'label': 'Do something that will look impressive in reverse'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 4,
   'adjustment': None,
   'points': 4,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.33,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 45,
   'task': {'value': 10,
    'label': 'Do something that will look impressive in reverse'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1=',
   'rigid': 5.0,
   'spread': 4.5,
   'scale': 4.17,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 46,
   'task': {'value': 10,
    'label': 'Do something that will look impressive in reverse'},
   'contestant': {'value': 6, 'label': 'Romesh Ranganathan'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1=',
   'rigid': 5.0,
   'spread': 4.5,
   'scale': 4.17,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 47,
   'task': {'value': 10,
    'label': 'Do something that will look impressive in reverse'},
   'contestant': {'value': 7, 'label': 'Tim Key'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '4',
   'rigid': 2.0,
   'spread': 2.0,
   'scale': 2.5,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 48,
   'task': {'value': 11, 'label': 'Unshackle yourself and sprint one metre'},
   'contestant': {'value': 3, 'label': 'Frank Skinner'},
   'base': 1,
   'adjustment': None,
   'points': 1,
   'rank': '5',
   'rigid': 1.0,
   'spread': 1.0,
   'scale': 1.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 49,
   'task': {'value': 11, 'label': 'Unshackle yourself and sprint one metre'},
   'contestant': {'value': 4, 'label': 'Josh Widdicombe'},
   'base': 3,
   'adjustment': None,
   'points': 3,
   'rank': '3',
   'rigid': 3.0,
   'spread': 3.0,
   'scale': 3.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None},
  {'id': 50,
   'task': {'value': 11, 'label': 'Unshackle yourself and sprint one metre'},
   'contestant': {'value': 5, 'label': 'Roisin Conaty'},
   'base': 5,
   'adjustment': None,
   'points': 5,
   'rank': '1',
   'rigid': 5.0,
   'spread': 5.0,
   'scale': 5.0,
   '5+3': None,
   '3+2': None,
   '3½+2½': None}],
 'truncated': False,
 'filtered_table_rows_count': 3975,
 'expanded_columns': ['contestant', 'task'],
 'expandable_columns': [[{'column': 'contestant',
    'other_table': 'people',
    'other_column': 'id'},
   'name'],
  [{'column': 'task', 'other_table': 'tasks', 'other_column': 'id'},
   'summary']],
 'columns': ['id',
  'task',
  'contestant',
  'base',
  'adjustment',
  'points',
  'rank',
  'rigid',
  'spread',
  'scale',
  '5+3',
  '3+2',
  '3½+2½'],
 'primary_keys': ['id'],
 'units': {},
 'query': {'sql': 'select id, task, contestant, base, adjustment, points, rank, rigid, spread, scale, [5+3], [3+2], [3½+2½] from normalized_scores order by id limit 51',
  'params': {}},
 'facet_results': {},
 'suggested_facets': [{'name': 'base',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=base'},
  {'name': 'adjustment',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=adjustment'},
  {'name': 'points',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=points'},
  {'name': 'rank',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=rank'},
  {'name': 'rigid',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=rigid'},
  {'name': 'spread',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=spread'},
  {'name': '5+3',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=5%2B3'},
  {'name': '3+2',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=3%2B2'},
  {'name': '3½+2½',
   'toggle_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_facet=3%C2%BD%2B2%C2%BD'}],
 'next': '50',
 'next_url': 'http://prettygr.im/tdlm/taskmaster/normalized_scores.json?_labels=on&_next=50',
 'private': False,
 'foreign': {'contestant': ['people',
   'id',
   'series',
   'seat',
   'name',
   'dob',
   'gender',
   'hand',
   'team',
   'champion',
   'TMI'],
  'task': ['tasks',
   'id',
   'series',
   'episode',
   'summary',
   'tags',
   'location',
   'points',
   'std',
   'TMI',
   'YT']},
 'allow_execute_sql': True,
 'query_ms': 44.12127588875592}

In [92]:
taskmaster_points = pd.DataFrame(columns=["id","task", "contestant", "base","adjustment","points","rank"])

In [93]:
for row in points_json['rows']:
    tm_id = row['id']
    task = row['task']['label']
    contestant = row['contestant']
    contestant = contestant['label']
    base = row['base']
    adjustment = row['adjustment']
    rank = row['rank']
    points = row['points']
    
    new_row = {"id":tm_id,"task": task, "contestant": contestant, "base":base, "adjustment":adjustment, "points":points,"rank":rank}
    
    taskmaster_points = pd.concat([taskmaster_points, pd.DataFrame([new_row])], ignore_index=True)

In [94]:
taskmaster_points

,id,task,contestant,base,adjustment,points,rank
0,1,The most unusual item,Frank Skinner,4,None,4,2
1,2,The most unusual item,Josh Widdicombe,1,None,1,5
2,3,The most unusual item,Roisin Conaty,2,None,2,4
3,4,The most unusual item,Romesh Ranganathan,3,None,3,3
4,5,The most unusual item,Tim Key,5,None,5,1
5,6,Eat as much watermelon as possible,Frank Skinner,2,None,2,4
6,7,Eat as much watermelon as possible,Josh Widdicombe,3,None,3,3
7,8,Eat as much watermelon as possible,Roisin Conaty,1,None,1,5
8,9,Eat as much watermelon as possible,Romesh Ranganathan,5,None,5,1
9,10,Eat as much watermelon as possible,Tim Key,4,None,4,2
10,11,Paint a horse while riding a horse,Frank Skinner,5,None,5,1
11,12,Paint a horse while riding a horse,Josh Widdicombe,3,None,3,3
12,13,Paint a horse while riding a horse,Roisin Conaty,1,None,1,5
13,14,Paint a horse while riding a horse,Romesh Ranganathan,4,None,4,2
14,15,Paint a horse while riding a horse,Tim Key,2,None,2,4
15,16,Empty the bathtub,Frank Skinner,4,None,4,2
16,17,Empty the bathtub,Josh Widdicombe,3,None,3,3
17,18,Empty the bathtub,Roisin Conaty,2,None,2,4
18,19,Empty the bathtub,Romesh Ranganathan,5,None,5,1
19,20,Empty the bathtub,Tim Key,1,None,1,5
20,21,Pop up a tent and pop on a onesie,Frank Skinner,4,None,4,2
21,22,Pop up a tent and pop on a onesie,Josh Widdicombe,3,None,3,3
22,23,Pop up a tent and pop on a onesie,Roisin Conaty,1,None,1,5
23,24,Pop up a tent and pop on a onesie,Romesh Ranganathan,2,None,2,4
24,25,Pop up a tent and pop on a onesie,Tim Key,5,None,5,1
25,26,Find Alex,Frank Skinner,0,None,0,None
26,27,Find Alex,Romesh Ranganathan,0,None,0,None
27,28,The most impressive item,Frank Skinner,4,None,4,2
28,29,The most impressive item,Josh Widdicombe,2,None,2,4
29,30,The most impressive item,Roisin Conaty,3,None,3,3
30,31,The most impressive item,Romesh Ranganathan,1,None,1,5
31,32,The most impressive item,Tim Key,5,None,5,1
32,33,High-five a 55-year-old,Frank Skinner,2,None,2,4
33,34,High-five a 55-year-old,Josh Widdicombe,5,None,5,1
34,35,High-five a 55-year-old,Roisin Conaty,4,None,4,2
35,36,High-five a 55-year-old,Romesh Ranganathan,1,None,1,5
36,37,High-five a 55-year-old,Tim Key,3,None,3,3
37,38,Identify the contents of the pies,Frank Skinner,1,None,1,5
38,39,Identify the contents of the pies,Josh Widdicombe,2,None,2,4
39,40,Identify the contents of the pies,Roisin Conaty,4,None,4,2
40,41,Identify the contents of the pies,Romesh Ranganathan,3,None,3,3
41,42,Identify the contents of the pies,Tim Key,5,None,5,1
42,43,Do something that will look impressive in reverse,Frank Skinner,1,None,1,5
43,44,Do something that will look impressive in reverse,Josh Widdicombe,4,None,4,3
44,45,Do something that will look impressive in reverse,Roisin Conaty,5,None,5,1=
45,46,Do something that will look impressive in reverse,Romesh Ranganathan,5,None,5,1=
46,47,Do something that will look impressive in reverse,Tim Key,3,None,3,4
47,48,Unshackle yourself and sprint one metre,Frank Skinner,1,None,1,5
48,49,Unshackle yourself and sprint one metre,Josh Widdicombe,3,None,3,3
49,50,Unshackle yourself and sprint one metre,Roisin Conaty,5,None,5,1